# Site wide configuration

title:            AngularBeers
locale:           en_US
url: http://localhost:4000


# Jekyll configuration

permalink:   /:categories/:title/
markdown:    kramdown
highlighter: pygments
sass:
  sass_dir: _sass
  style: compressed
gems:
  - jekyll-sitemap

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: false


# Site owner
owner:
  name: Angular & Beers
  avatar: angular-beers.png
  bio: "AngularJS & Beers. Non-profit event format to socialise with AngularJS people. ^_^ #angularjs #angularbeers #barcelona"
  email: info@angularbeers.com
  disqus-shortname:
  twitter: angularbeers
  facebook: AngularBeers
  google:
    plus: AngularBeers
    analytics: UA-837977-25
    verify:
    ad-client:
    ad-slot:
  bing-verify:
  github: AngularBeers
  stackoverflow: #http://stackoverflow.com/users/123456/username
  linkedin: #username
  xing: #username
  instagram: #username
  lastfm: #username
  tumblr: #username
  pinterest: #username
  foursquare: #username
  steam: #username
  dribbble: #username
  youtube: angularbeers
  soundcloud: #username
  weibo: #username
  flickr: #username

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md"]
